language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  email: false
